### ISSUE TITLE
Relative paths not accepted by Linux

### ISSUE THREAD

**Issue by backseatviolist** [crucialfelix/supercolliderjs#12]
Using Ubuntu 14.04. The `supercollider` binary does not seem to accept relative file names:

    $ supercollider impromptu.scd 
    [a whole bunch of loading messages]
    file "impromptu.scd" does not exist.

The file runs successfully if I supply `/home/nathan/impromptu.scd`. This contradicts the documentation, which provides an example using a relative file name.

**Comment by crucialfelix** [comment]
Sorry I didn't get this notification and forgot to reply to this !  I think I already fixed it, will confirm
