### ISSUE TITLE
scsynth doesn't support command-line arguments other than UDP port

### ISSUE THREAD

**Issue by snappizz** [crucialfelix/supercolliderjs#26]
Again, I'm on Ubuntu 16.04, launching scsynth with the below code:

```
var sc = require("supercolliderjs");
sc.server.boot({
    scsynth: "/home/nathan/usr/local/bin/scsynth"
});
```

SuperCollider launches successfully and I can play Synths with it. However, it doesn't connect to the system inputs and outputs in JACK, as can be seen in this Patchage screenshot:

![untitled](https://cloud.githubusercontent.com/assets/1211064/21579470/23eeca0a-cf66-11e6-997a-428ad40927e9.png)

It's also odd that it has eight inputs and outputs, when the default supercollider.js settings have `numInputBusChannels/numOutputBusChannels` both set to 2. It looks like the command-line arguments to scsynth are getting dropped somehow.

**Comment by snappizz** [comment]
Ah. Args other than the UDP port are [not implemented](https://github.com/crucialfelix/supercolliderjs/blob/develop/src/server/server.js#L195). Is there any way I can hack around this?

**Comment by crucialfelix** [comment]
I should implement them ! And provide a way to add arbitrary ones in case the api gets out of sync.
