### ISSUE TITLE
error  : Failed to boot /usr/local/bin/scsynth 

### ISSUE THREAD

**Issue by DiegOrtega** [crucialfelix/supercolliderjs#31]
![captura de pantalla 2017-05-09 a las 0 40 47](https://cloud.githubusercontent.com/assets/11580196/25836906/33cf6ca0-3450-11e7-9276-672e8dd55f36.png)

Does anyone knows how can I solve this?

**Comment by crucialfelix** [comment]
ENOENT means "No such file or directory"

Do you have scsynth installed at `/usr/local/bin/scsynth` ?

**Comment by crucialfelix** [comment]
Same as for the other issue.  See guide for how to configure here: https://crucialfelix.gitbooks.io/supercollider-js-guide/content/lang/install-and-configuration.html

You can also just pass it in to boot

```js
sc.server.boot({ scsynth: '/path/to/your/scsynth' }).then ...
```

**Comment by DiegOrtega** [comment]
Thanks a lot!
