### ISSUE TITLE
[suggestion/discussion] - integration with maxmsp js object of the supercollider.js client , and doing the same with the supercollider link quark

### ISSUE THREAD

**Issue by ghost** [crucialfelix/supercolliderjs#40]
[suggestion/discussion] - integration with maxmsp/m4l js object of the supercollider.js client, and doing the same with the supercollider link quark

Heyho

IMHO, it would be quite interesting to:
- make an integration of this client with maxmsp js object

a cool way to do this, would be, in my perspective:
- allowing for a decent integration of the supercollider.js client within js object of maxmsp/maxforlive
- creating a c++ client maxmsp object, that would serve as a router for the many outputs of scsynth signals

the main advantage of such a thing on the long run would be, IMHO:
- allowing for a perfect integration fo supercollider.js within maxforlive, and allowing the Ableton link quark to co-operate within the scope of this process

this would quickly allow to:
- expanding very fast the overall sets of possibilities of shared environment between Ableton, m4l, and supercollider

furthermore, it would be interesting, to also consider for integration, in a pretty similar fashion,
- integrating supercollider.js within processing.js
- integrating supercollider.js within three.js
- integrating supercollider.js within p5.js
- integrating supercollider.js within unity

I am perfectly aware that:
- this demands time, and supercollider.js is mostly maintained by a single person, and there will not possibly be a consensus in relation to how to maintain such a thing in the long run

even though:
- definitely worth considering (at least in my personal perspective)

**Comment by tem44** [comment]
well, there's always the chance of using something as simple as NDefs, and OSC messages for getting these things to talk to each other. even though it would be quite cool to make such integration

**Comment by crucialfelix** [comment]
I'm actually quite close friends with Jeremy from Cycling74 and we've discussed the various cool things they are up to with JavaScript.

I'm always in support of opening connections and integrations. I do think that this should be a separate package. Node / js things should generally be in the smallest possible packages and be open to connecting with other things.

I wish I had more time to work on my dryadic project. This is something that can control supercollider.js and many other things as well and connect them. That's the kind of umbrella system I would like.

I think the best approach is to present problems and difficulties in getting supercollider.js to act like a good independent client.

**Comment by tem44** [comment]
well, I also have friends in cycling74. I know one guy who helps them set documentation for new max releases, and helps them by making workshops in demand. he attended the same school I attended perhaps some 10 or 20 years before I was there, and he has a couple releases in my record label.

Of course that keeping packages as minimal as possible is a good and decent solution. this was meant to be integrated into node.js, and that's it. Max 8 seems to have better support for javascript and node.js in general. I didn't dwell into it pretty extensively yet, but yes, it definitely brings in some very cool, and interesting news. I bought the maforlive+ableton live 10 standard license. It seems pretty cool, and I do honestly hope to see what can I do with node.js there. 

One of my current makings focuses is making a system for making automated searches on the internet via react.js/node.js and UNIX/shell/bash basic dumb commands

I didn't think about it that way, but maybe interfacing between it and maxmsp/maxforlive via js object may be a decent thing to do.

regarding binding node.js or max/maxforlive with supercollider via javascript is too much of a work and there may be other priorities for you at the moment, but as I said if you want to make a simple standalone for Mac or Linux, and set up some classes with synthesis definitions, and triggering and controlling them via OpenSoundControl for the sake of doing sound design is a nice (you can always route the audio via Jack router)

finally, while it's cool to evolve software technically wise, and figuring out new ways of doing certain things, learning about coding, and finally making stuff, you can always do the following: record some sound in Supercollider and grabbing them into Ableton Live or MaxMSP or Maxforlive, or whatever you want to use for that same endeavor.

that's it - cheers

**Comment by tem44** [comment]
feel free to dismiss the issue. if you want to leave it open for people to check out - someone may eventually think about grabbing the idea for doing something - please do so. cheers
