### ISSUE TITLE
Interact with existing supercollider process?

### ISSUE THREAD

**Issue by leshy** [crucialfelix/supercolliderjs#41]
Hey, is there an easy way to connect to an existing scsynth instance and then play with it from node in parallel with my supercollider IDE?

tnx!

**Comment by leshy** [comment]
Thanks for the quick reply, just to document this for others

```js
ServerPlus = require('supercolliderjs/lib/server/ServerPlus.js').default
new ServerPlus().connect()
```

needed to increase number of users in scsynth (default seems to be 1) by adding
```
s.options.maxLogins = 8;
```
to the supercollider init script

**Comment by crucialfelix** [comment]
Ah, I see that ServerPlus isn't exported at the top level. 

It's technically still in ALPHA but I really want to do a new release soon.

https://github.com/crucialfelix/supercolliderjs/blob/develop/src/server/index.js

Glad to hear it works for you. Don't hesitate to ask me about anything or share any problems you are running into.
