### ISSUE TITLE
jack error output on boot

### ISSUE THREAD

**Issue by htor** [crucialfelix/supercolliderjs#56]
when booting supercolliderjs with `sc.lang.boot()` it spits out the following error aboug JACK:

```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
```
 i know these are not critical errors, since i'm not using jack, but i'm curious why are they appearing in first place? would like to to start supercolliderjs without any errors in my logs, if possible.

**Comment by crucialfelix** [comment]
It is an error being posted from scsynth. It seems that it happens often for audio programs that use ALSA.

eg:
https://ubuntuforums.org/showthread.php?t=1867298

> I installed jackd (sudo apt-get install jackd).
> Then I added this command to my startup programs: jackd -d dummy

https://github.com/samaaron/sonic-pi/issues/1884

**Comment by htor** [comment]
i see, so this is nothing we control from supercolliderjs? by the way i'm on macos and i have JackPilot.app installed. could it be that scsynth detects that it is installed and is trying to connect?

**Comment by crucialfelix** [comment]
I would expect that it has to be running.

Look in your macOS audio preferences.  Maybe something is there that triggers it.

You can definitely get a good fast answer on the sc-users lists or on the FB group. I don't think I've used Jack more than once ever.
